https://huggingface.co/datasets/storytracer/LoC-PD-Books

In [2]:
import pandas as pd
temp = None
for i in range(1,10):
    df = pd.read_parquet(f"base_dbs/LoC-PD-Books/train_0000{i}.parquet")
    df["category"] = "book"
    temp = pd.concat([temp, df], ignore_index=True)
temp

,lccn,title,author,year,page_count,filename,text,category
0,24024079,"Faith at work,","Trowbridge, Gertrude Mary (Sherman)",1924,88,faithatwork00trow_djvu.txt,\n\n\n\nClass _ BN/'W *5 \n\nBook_ ‘AH _ \n\nC...,book
1,17023956,"Straws from the manager; or, Thoughts on Chris...","Cotter, James Henry",1917,118,strawsfrommanage00cott_djvu.txt,\nClass \n\nBook \n\n\n\nCOPYRIGHT DEPOSIE \n\...,book
2,unk81039814,A Christmas meditation.,"Gilman, Lawrence",1916,32,christmasmeditat00gilm_djvu.txt,. \n\n\n\n\nmm$ \n\n\n\nA CHIUSTMAS \nMEDITATI...,book
3,unk81010574,Bethlehem bells.,"Hoadley, B. J.",1912,72,bethlehembell00hoad_djvu.txt,\n\n\nB V \n\n45 \n\n\n\n\n\nClass \n\nBook \n...,book
4,09022920,"Christmas builders,","Jefferson, Charles Edward",1909,56,christmasbuilder00jeff_djvu.txt,BV \n\n\n\n45 CHRISTMAS \n^^'^ BUILDERS \n\n\n...,book
...,...,...,...,...,...,...,...,...
8732,05033608,The horse in America; a practical treatise on ...,"Speed, John Gilmer",1905,362,horseinamericapr01spee_djvu.txt,\n\n\n\n** \n\n\n\n■On . . * f.* ^-^ ♦^^'^ . 4...,book
8733,09029441,"Horse secrets, written,","Alexander, Alexander S.",1909,68,horsesecretswrit00alex_djvu.txt,\n\n\n\n\nt^-hf^if^- \n\n\n\n\nPublished bv \n...,book
8734,13025721,"Horse secrets written, comp. and now disclosed","Alexander, Alexander S.",1913,68,horsesecretswrit01alex_djvu.txt,SF 285 \n.P62 \n1913 \nCopy 1 \n\n\n\n\n\n\nn ...,book
8735,agr21000011,Cottonseed meal for horses.,"Bell, George A. (George Arthur)",1920,16,cottonseedmealfo00bell_djvu.txt,* \n\n\n\nsp its- \n\n\n\nH \n\n\n\n/v/C- ?zt ...,book
8736,11028083,"The horse; his breeding, care and use,","Buffum, David",1911,176,horsehisbreeding01buff_djvu.txt,\nTHEHORS \n\nHis Breeding \n\n\n\n\nT \n\ns \...,book

In [3]:
temp = temp[['text', 'year', 'category']]
temp["decade"] = (temp["year"] // 10) * 10
temp

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_15076\3049691051.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["decade"] = (temp["year"] // 10) * 10

                                                   text  year category  decade
0     \n\n\n\nClass _ BN/'W *5 \n\nBook_ ‘AH _ \n\nC...  1924     book    1920
1     \nClass \n\nBook \n\n\n\nCOPYRIGHT DEPOSIE \n\...  1917     book    1910
2     . \n\n\n\n\nmm$ \n\n\n\nA CHIUSTMAS \nMEDITATI...  1916     book    1910
3     \n\n\nB V \n\n45 \n\n\n\n\n\nClass \n\nBook \n...  1912     book    1910
4     BV \n\n\n\n45 CHRISTMAS \n^^'^ BUILDERS \n\n\n...  1909     book    1900
...                                                 ...   ...      ...     ...
8732  \n\n\n\n** \n\n\n\n■On . . * f.* ^-^ ♦^^'^ . 4...  1905     book    1900
8733  \n\n\n\n\nt^-hf^if^- \n\n\n\n\nPublished bv \n...  1909     book    1900
8734  SF 285 \n.P62 \n1913 \nCopy 1 \n\n\n\n\n\n\nn ...  1913     book    1910
8735  * \n\n\n\nsp its- \n\n\n\nH \n\n\n\n/v/C- ?zt ...  1920     book    1920
8736  \nTHEHORS \n\nHis Breeding \n\n\n\n\nT \n\ns \...  1911     book    1910

[8737 rows x 4 columns]

In [ ]:
df = pd.read_parquet("large_dataset.parquet")
df = pd.concat([df, temp], ignore_index=True)
df.to_parquet("large_dataset.parquet")
df.head()