https://huggingface.co/datasets/storytracer/LoC-PD-Books

In [1]:
import pandas as pd
temp = None
for i in range(1,8):
    df = pd.read_parquet(f"base_dbs/LoC-PD-Books/train_0000{i}.parquet")
    df["category"] = "book"
    temp = pd.concat([temp, df], ignore_index=True)
temp

,lccn,title,author,year,page_count,filename,text,category
0,24024079,"Faith at work,","Trowbridge, Gertrude Mary (Sherman)",1924,88,faithatwork00trow_djvu.txt,\n\n\n\nClass _ BN/'W *5 \n\nBook_ ‘AH _ \n\nC...,book
1,17023956,"Straws from the manager; or, Thoughts on Chris...","Cotter, James Henry",1917,118,strawsfrommanage00cott_djvu.txt,\nClass \n\nBook \n\n\n\nCOPYRIGHT DEPOSIE \n\...,book
2,unk81039814,A Christmas meditation.,"Gilman, Lawrence",1916,32,christmasmeditat00gilm_djvu.txt,. \n\n\n\n\nmm$ \n\n\n\nA CHIUSTMAS \nMEDITATI...,book
3,unk81010574,Bethlehem bells.,"Hoadley, B. J.",1912,72,bethlehembell00hoad_djvu.txt,\n\n\nB V \n\n45 \n\n\n\n\n\nClass \n\nBook \n...,book
4,09022920,"Christmas builders,","Jefferson, Charles Edward",1909,56,christmasbuilder00jeff_djvu.txt,BV \n\n\n\n45 CHRISTMAS \n^^'^ BUILDERS \n\n\n...,book
...,...,...,...,...,...,...,...,...
6803,24000553,"Tribute to old Lancaster, city--county, Pennsy...","Riddle, William",1908,154,tributetooldlanc00ridd_djvu.txt,"\nR 1 D D i. E \n\n\n\n\n\n\n\n\n^<Wt7^<^-t^-,...",book
6804,01016609,Lancaster townstead.,"Sener, Samuel Miller",1901,18,lancastertownste00sener_djvu.txt,# \n\n\n\n\n\nz^^-^ \n\n\n\nF 159 \n.L2 S5 \nC...,book
6805,07018194,An outline history of a church; a memorial of ...,"Whitteker, John E. (John Edwin)",1905,48,outlinehistoryof00whitt_djvu.txt,F 159 \n.L2 W6 \nCopy 1 \n\n\n\n\nThe 175th An...,book
6806,09012040,"Lansdowne past and present, 1888. 1908.","Johnson, George Caldwell",1908,104,lansdownepastpre00john_djvu.txt,\n\n\n\n\nXans^ownc \n\npast \n\n\n\nan6 \n\n\...,book
6807,24015023,"The history of St. John's Reformed Church, 185...","Ranck, Henry H. (Henry Haverstick)",1901,276,historyofstjohns00ranc_djvu.txt,"\nass. \n\n\n\nPRi:;sENTi:n r,Y \n\n\n\n-r- ' ...",book

In [2]:
temp = temp[['text', 'year', 'category']]
temp["decade"] = (temp["year"] // 10) * 10
temp

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8176\3049691051.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["decade"] = (temp["year"] // 10) * 10

                                                   text  year category  decade
0     \n\n\n\nClass _ BN/'W *5 \n\nBook_ ‘AH _ \n\nC...  1924     book    1920
1     \nClass \n\nBook \n\n\n\nCOPYRIGHT DEPOSIE \n\...  1917     book    1910
2     . \n\n\n\n\nmm$ \n\n\n\nA CHIUSTMAS \nMEDITATI...  1916     book    1910
3     \n\n\nB V \n\n45 \n\n\n\n\n\nClass \n\nBook \n...  1912     book    1910
4     BV \n\n\n\n45 CHRISTMAS \n^^'^ BUILDERS \n\n\n...  1909     book    1900
...                                                 ...   ...      ...     ...
6803  \nR 1 D D i. E \n\n\n\n\n\n\n\n\n^<Wt7^<^-t^-,...  1908     book    1900
6804  # \n\n\n\n\n\nz^^-^ \n\n\n\nF 159 \n.L2 S5 \nC...  1901     book    1900
6805  F 159 \n.L2 W6 \nCopy 1 \n\n\n\n\nThe 175th An...  1905     book    1900
6806  \n\n\n\n\nXans^ownc \n\npast \n\n\n\nan6 \n\n\...  1908     book    1900
6807  \nass. \n\n\n\nPRi:;sENTi:n r,Y \n\n\n\n-r- ' ...  1901     book    1900

[6808 rows x 4 columns]

In [4]:
df = pd.read_parquet("large_dataset.parquet")
df = pd.concat([df, temp], ignore_index=True)
df.to_parquet("large_dataset.parquet")
df.head()

                                                text    year category  decade
0  Republic Of Coi0atbid.---Wc publish observes i...  1825.0     None  1820.0
1  permit from ther owners, employers, or guard i...  1853.0     None  1850.0
2  Representatives Of the United States an Con-\n...  1867.0     None  1860.0
3  'csSei u icBai certainty COhccinin5 thc\n\ncha...  1862.0     None  1860.0
4  WIDENER HN BWGN X\n\nMYTHOLOGY FOR MODERNS JAM...  1899.0     None  1890.0

In [6]:
df.shape

(245730, 4)