In [22]:
import pandas as pd
df = pd.DataFrame({"decade": [], "year": [], "text": [], "category": []})

In [23]:
df.to_parquet("large_dataset.parquet")

In [24]:
df = pd.read_parquet("large_dataset.parquet")
df

Empty DataFrame
Columns: [decade, year, text, category]
Index: []

In [30]:
temp = pd.read_csv("base_dbs/textage_large.csv")
temp.head()

,text,category,date,title,author,decade,text_length
0,hEre begynneth the volume intituled and named ...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,2890
1,O P A I K L A K In three books The first leaf ...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,2940
2,quayersleyda partandin two yere aftyrlabouredn...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,3116
3,Iupiter andof the begynnyngandcomyng vp of Tro...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,3394
4,comyn w lehe wasrecomandedsolempnly andcalleda...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,3338

In [31]:
temp["year"] = temp["date"].astype(int)
temp.drop(['title', 'text_length', 'author', 'year'], axis=1, inplace=True)
temp.head()

                                                text category  date  decade
0  hEre begynneth the volume intituled and named ...     Book  1473    1470
1  O P A I K L A K In three books The first leaf ...     Book  1473    1470
2  quayersleyda partandin two yere aftyrlabouredn...     Book  1473    1470
3  Iupiter andof the begynnyngandcomyng vp of Tro...     Book  1473    1470
4  comyn w lehe wasrecomandedsolempnly andcalleda...     Book  1473    1470

In [38]:
df.head(100000)

,text,category,date,decade
0,hEre begynneth the volume intituled and named ...,Book,1473,1470
1,O P A I K L A K In three books The first leaf ...,Book,1473,1470
2,quayersleyda partandin two yere aftyrlabouredn...,Book,1473,1470
3,Iupiter andof the begynnyngandcomyng vp of Tro...,Book,1473,1470
4,comyn w lehe wasrecomandedsolempnly andcalleda...,Book,1473,1470
...,...,...,...,...
91913,Yet I was disturbed to learn the facts and hav...,Book,1921,1920
91914,do not know whe ther my mother is still alive ...,Book,1921,1920
91915,a teacher of the Law Have you forgotten this b...,Book,1921,1920
91916,him ask whether someone might be hiding her fr...,Book,1921,1920
91917,BC THE ECLOGUES by Virgil ECLOGUE I MELIBOEUS ...,Book,1921,1920