https://huggingface.co/datasets/mhla/pre1900-corpus

In [21]:
import pandas as pd

In [22]:
df = pd.read_parquet("base_dbs/shard_00040.parquet")
df

,text,year,title,source,ocr_score,legibility
0,Republic Of Coi0atbid.---Wc publish observes i...,1825,"Richmond enquirer. [volume] (Richmond, Va.) 18...",AmericanStories,-1.00,1.0
1,"permit from ther owners, employers, or guard i...",1853,The national era. [volume] (Washington [D.C.])...,AmericanStories,-1.00,1.0
2,Representatives Of the United States an Con-\n...,1867,"Alexandria gazette. [volume] (Alexandria, D.C....",AmericanStories,-1.00,1.0
3,'csSei u icBai certainty COhccinin5 thc\n\ncha...,1862,"Marshall County Republican. (Plymouth, Ind.) 1...",AmericanStories,-1.00,1.0
4,WIDENER HN BWGN X\n\nMYTHOLOGY FOR MODERNS JAM...,1899,Mythology for moderns an up-to-date text-book ...,institutional-books,0.99,-1.0
...,...,...,...,...,...,...
49995,"ion, that no potato eating nation has ever r g...",1841,"Burlington free press. [volume] (Burlington, V...",AmericanStories,-1.00,1.0
49996,appointed. and no Mussulman power can now stop...,1867,The New York herald. [volume] (New York [N.Y.]...,AmericanStories,-1.00,1.0
49997,MS WORST enemy from drowning. AuOLneE Is maple...,1899,"Evening star. [volume] (Washington, D.C.) 1854...",AmericanStories,-1.00,1.0
49998,Tile Ou Vi OcDItIuUtT. ne mas also Ocon III vi...,1889,"The Austin weekly statesman. (Austin, Tex.) 18...",AmericanStories,-1.00,1.0
49999,"Betty-Polly -Jenny-E, iza-both -my-my- : my-sa...",1840,"The pilot and transcript. [volume] (Baltimore,...",AmericanStories,-1.00,1.0

In [23]:
df.drop(["title","source","ocr_score","legibility"],axis=1,inplace=True)

In [24]:
df["category"] = None

In [25]:
df["decade"] = (df["year"] - (df["year"]%10))
df

,text,year,category,decade
0,Republic Of Coi0atbid.---Wc publish observes i...,1825,None,1820
1,"permit from ther owners, employers, or guard i...",1853,None,1850
2,Representatives Of the United States an Con-\n...,1867,None,1860
3,'csSei u icBai certainty COhccinin5 thc\n\ncha...,1862,None,1860
4,WIDENER HN BWGN X\n\nMYTHOLOGY FOR MODERNS JAM...,1899,None,1890
...,...,...,...,...
49995,"ion, that no potato eating nation has ever r g...",1841,None,1840
49996,appointed. and no Mussulman power can now stop...,1867,None,1860
49997,MS WORST enemy from drowning. AuOLneE Is maple...,1899,None,1890
49998,Tile Ou Vi OcDItIuUtT. ne mas also Ocon III vi...,1889,None,1880
49999,"Betty-Polly -Jenny-E, iza-both -my-my- : my-sa...",1840,None,1840

In [26]:
temp = pd.read_parquet("large_dataset.parquet")
temp = pd.concat([df, temp], ignore_index=True)
temp.to_parquet("large_dataset.parquet")
temp.head()

                                                text    year category  decade
0  Republic Of Coi0atbid.---Wc publish observes i...  1825.0     None  1820.0
1  permit from ther owners, employers, or guard i...  1853.0     None  1850.0
2  Representatives Of the United States an Con-\n...  1867.0     None  1860.0
3  'csSei u icBai certainty COhccinin5 thc\n\ncha...  1862.0     None  1860.0
4  WIDENER HN BWGN X\n\nMYTHOLOGY FOR MODERNS JAM...  1899.0     None  1890.0

In [27]:
temp.shape

(238922, 4)