In [8]:
import pandas as pd
temp = pd.read_csv("base_dbs/textage_large.csv")
temp.head()

,text,category,date,title,author,decade,text_length
0,hEre begynneth the volume intituled and named ...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,2890
1,O P A I K L A K In three books The first leaf ...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,2940
2,quayersleyda partandin two yere aftyrlabouredn...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,3116
3,Iupiter andof the begynnyngandcomyng vp of Tro...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,3394
4,comyn w lehe wasrecomandedsolempnly andcalleda...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,3338

In [9]:
temp["year"] = temp["date"].astype(int)
temp.drop(['title', 'text_length', 'author', 'date'], axis=1, inplace=True)
temp.head()

                                                text category  decade  year
0  hEre begynneth the volume intituled and named ...     Book    1470  1473
1  O P A I K L A K In three books The first leaf ...     Book    1470  1473
2  quayersleyda partandin two yere aftyrlabouredn...     Book    1470  1473
3  Iupiter andof the begynnyngandcomyng vp of Tro...     Book    1470  1473
4  comyn w lehe wasrecomandedsolempnly andcalleda...     Book    1470  1473

In [10]:
df = pd.read_parquet("large_dataset.parquet")
df = pd.concat([df, temp], ignore_index=True)
df.to_parquet("large_dataset.parquet")
df.head()

   decade    year                                               text category
0  2010.0  2013.0                                                Bed    tweet
1  2010.0  2013.0  I felt my first flash of violence at some fool...    tweet
2  2010.0  2013.0            Ladies drink and get in free till 10:30    tweet
3  2010.0  2013.0  Watching #Miranda On bbc1!!! @mermhart u r HIL...    tweet
4  2010.0  2013.0          Shopping! (@ Kohl's) http://t.co/I8ZkQHT9    tweet